apiVersion: v1
kind: Pod
metadata:
    name: test-mysql
spec:
    containers:
    - name: test-mysql
      image: mysql:5.7
      imagePullPolicy: IfNotPresent
      env:
      - name:  MYSQL_ROOT_PASSWORD
        value: "redhat"
      - name: MYSQL_DATABASE
        value: "school"   
      ports:
      - containerPort: 3306
      resources:
        requests:
            memory: "1G"
            cpu: "1"
        limits:
            memory: "2G"
            cpu: 2


