apiVersion: v1

kind: Pod

metadata:
    name: test1
    namespace: web

spec:
    containers:
        - name: test1
          image: centos:7
          command:
              - sleep
              - "3600"
