apiVersion: apps/v1

kind: Deployment

metadata:
    name: nginx-test
    namespace: kk

spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx

    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1

    template:
        metadata:
            labels:
                app: nginx

        spec:
            containers:
            - name: nginx-test
              image: nginx:1.18
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 80



            
        
        

