apiVersion: apps/v1
kind: Deployment
metadata: 
    name: test
    namespace: kk
spec:
    replicas: 6
    selector:
        matchLabels:
            app: centos7
    template:
        metadata:
            labels:
                app: centos7

        spec:
            containers:
                - name: test1
                  image: centos:7
                  imagePullPolicy: IfNotPresent
                  command:
                    - sleep
                    - "3600"
    
