apiVersion: batch/v1

kind: Job
metadata:
    name: test-job
spec:
    template:
        metadata:
            name: test-job

        spec:
            restartPolicy: Never
            containers:
                - name: test-job
                  image: centos:7
                  imagePullPolicy: IfNotPresent
                  command:
                    - "/bin/bash"
                    - "-c"
                    - "for i in 1 3 4 5 ;do echo $i; done"
