apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data02
spec:
    capacity:
        storage: 5G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.47.202
        path: /data02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-vpc
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5G
