apiVersion: apps/v1
kind: StatefulSet

metadata:
    name: test-mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: test-mysql
    
    serviceName: "test-mysql"
    template:
        metadata:
            labels:
                app: test-mysql
        spec:
            containers:
            - name: test-sql
              image: mysql:5.7
              imagePullPolicy: IfNotPresent
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: redhat
              volumeMounts:
                - name: mysql-data-volume
                  mountPath: /var/lib/mysql
            volumes:
                - name: mysql-data-volume
                  persistentVolumeClaim:
                    claimName: mysql-vpc
