apiVersion: apps/v1
kind: Deployment

metadata:
    name: test-nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            web: nginx

    template:
        metadata:
            labels:
                web: nginx

        spec:
            containers:
            - name: nginx
              image: nginx:1.16
              imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
    name: nginx-nodeport
spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 30002
    selector:
        web: nginx
    


