apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: test-nginx
              image: nginx:1.18
              imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Service
metadata:
    name: test-nginx
spec:
    ports:
    - port: 80
    selector:
        app: nginx


         
    
