apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data-3g
spec:
    capacity:
        storage: 3G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.47.202
        path: /data01


