apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data-5g
spec:
    capacity:
        storage: 5G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.47.202
        path: /data02


